<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active processes:' => 'Активні процеси:',
    'All dumps successfully removed.' => 'Всі дампи успішно видалені.',
    'Are you sure?' => 'Ви впевнені?',
    'Create dump' => 'Створити дамп',
    'Create time' => 'Час створенния',
    'Custom dump preset' => 'Свій шаблон налагоджень для дампа',
    'Custom restore preset' => 'Свій шаблон налагоджень для відновлень',
    'DB manager' => 'БД менеджер',
    'Database' => 'База даних',
    'Delete' => 'Видалити',
    'Delete all' => 'Видалити все',
    'Download' => 'Завантажити',
    'Dump deleted successfully.' => 'Дамп успішно видалено.',
    'Dump failed.' => 'Помилка створенния дампа.',
    'Dump only schema' => 'Дамп структури без даних',
    'Dump request invalid.' => 'Помилка запиту дампа.',
    'Dump successfully created.' => 'Дамп успішно створено.',
    'Dump successfully restored.' => 'Дамп успішно відновлено.',
    'Error deleting dump.' => 'Помилка видаленння дампа.',
    'Error deleting dumps.' => 'Помилка видаленння дампів.',
    'Name' => 'Назва',
    'Process complete!' => 'Завдання випконано!',
    'Process running with pid={pid}' => 'Процес розпочато з pid={pid}',
    'Restore' => 'Відновити',
    'Restore failed.' => 'Помилка відновлення.',
    'Run in background' => 'Запустити фоновим процесом',
    'Size' => 'Размір',
    'Type' => 'Тип',
    'gzip' => '',
];
